const cardRarityTypes = [
  "all",
  "Common",
  "Uncommon",
  "Rare",
  "Rare Holo",
  "Rare Ultra",
  "Rare Secret",
  "Rare Rainbow",
  "Rare Holo GX",
  "Rare Holo EX",
  "Rare Holo V",
  "Rare Holo VMAX",
  "Rare Holo VSTAR",
  "Rare PRIME",
  "Rare BREAK",
  "Rare Prism Star",
  "Rare ACE",
  "Amazing Rare",
  "Legend",
  "Promo",
  "Classic Collection",
  "Trainer Gallery Rare Holo",
  "Radiant Rare",
  "Illustration Rare",
  "Special Illustration Rare",
  "Hyper Rare",
  "Double Rare",
  "Triple Rare",
  "ACE SPEC Rare",
  "Shiny Rare",
  "Shiny Ultra Rare"
];

export default cardRarityTypes;